apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: yolo-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yolo-dev-controller-admin
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: yolo-dev
roleRef:
  kind: ClusterRole
  name: yolo-dev-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: yolo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: github.com/yolo3301/kcrd/cmd/controller